-- SHOPGRAB ASSIGNMENT DDL
-- STEP 0: DROP EXISTING TABLES (SAFE RE-RUN)

SET DEFINE OFF;

DROP TABLE VOUCHER_REDEMPTION CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DELIVERY CASCADE CONSTRAINTS PURGE;
DROP TABLE DELIVERY_COMPANY CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE GROUP_ORDER_PARTICIPANT CASCADE CONSTRAINTS PURGE;
DROP TABLE GROUP_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE VOUCHER CASCADE CONSTRAINTS PURGE;
DROP TABLE MENU_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE ITEM_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTAURANT_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE ADDRESS CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER_TYPE CASCADE CONSTRAINTS PURGE;
