-- TEAM ASSIGNMENT OBJECT DROP
-- SAFE RE-RUN: DROP ONLY OBJECTS CREATED BY TEAM SCRIPTS

SET DEFINE OFF;

PROMPT Dropping views...
DROP VIEW M1_V_MEMBER_PROFILE;
DROP VIEW M1_V_MEMBER_ORDER_ACTIVITY;
DROP VIEW M2_V_RESTAURANT_MENU;
DROP VIEW M2_V_RESTAURANT_ORDER_OVERVIEW;
DROP VIEW M3_V_ORDER_ITEM_DETAIL;
DROP VIEW M3_V_ORDER_PAYMENT_DETAIL;
DROP VIEW M4_V_GROUP_ORDER_OVERVIEW;
DROP VIEW M4_V_GROUP_PARTICIPANT_DETAIL;
DROP VIEW M5_V_DELIVERY_TRACKING;
DROP VIEW M5_V_VOUCHER_REDEMPTION_DETAIL;

PROMPT Dropping procedures and report procedures...
DROP PROCEDURE PRC_M1_REGISTER_MEMBER;
DROP PROCEDURE PRC_M1_GET_MEMBER_PROFILE;
DROP PROCEDURE PRC_M2_CREATE_ADDRESS;
DROP PROCEDURE PRC_M2_SET_DEFAULT_ADDRESS;
DROP PROCEDURE PRC_M3_REGISTER_RESTAURANT;
DROP PROCEDURE PRC_M3_UPD_REST_PROFILE;
DROP PROCEDURE PRC_M4_CREATE_MENU_ITEM;
DROP PROCEDURE PRC_M4_GET_MENU_ITEM_DETAIL;
DROP PROCEDURE PRC_M5_CREATE_CUSTOMER_ORDER;
DROP PROCEDURE PRC_M5_RECORD_PAYMENT;
DROP PROCEDURE RPT_M1_MONTHLY_SALES_SUMMARY;
DROP PROCEDURE RPT_M1_RESTAURANT_PERFORMANCE;
DROP PROCEDURE RPT_M2_MEMBER_ORDER_HISTORY;
DROP PROCEDURE RPT_M2_VOUCHER_REDEMPTION;
DROP PROCEDURE RPT_M3_GROUP_ORDER_SUMMARY;
DROP PROCEDURE RPT_M3_GROUP_ORDER_DETAIL;
DROP PROCEDURE RPT_M4_DELIVERY_SERVICE;
DROP PROCEDURE RPT_M4_PICKUP_VS_DELIVERY;
DROP PROCEDURE RPT_M5_TOP_SELLING_ITEMS;
DROP PROCEDURE RPT_M5_GROUP_PARTICIPANT_ITEMS;
DROP PROCEDURE RPT_M5_MEMBER_SPEND_ANALYSIS;
-- Transitional cleanup for old report names (safe to keep; ignored if missing)
DROP PROCEDURE RPT_M1_MEMBER_SUMMARY;
DROP PROCEDURE RPT_M1_RESTAURANT_OVERVIEW;
DROP PROCEDURE RPT_M2_GROUP_ORDER_DETAIL;
DROP PROCEDURE RPT_M2_MEMBER_GROUP_ACTIVITY;
DROP PROCEDURE RPT_M3_ORDER_PAYMENT_SUMMARY;
DROP PROCEDURE RPT_M3_MEMBER_SPEND_REPORT;
DROP PROCEDURE RPT_M4_RESTAURANT_SALES;
DROP PROCEDURE RPT_M4_DELIVERY_STATUS_REPORT;
DROP PROCEDURE RPT_M5_VOUCHER_USAGE;
DROP PROCEDURE RPT_M5_PAYMENT_COLLECTION;

PROMPT Dropping triggers...
DROP TRIGGER TRG_M1_MEMBER_VALIDATE_BIU;
DROP TRIGGER TRG_M1_ADDRESS_DEFAULT_CT;
DROP TRIGGER TRG_M2_RESTAURANT_VALIDATE_BIU;
DROP TRIGGER TRG_M2_MENU_ITEM_PROMO_BIU;
DROP TRIGGER TRG_M3_GROUP_ORDER_RULES_BIU;
DROP TRIGGER TRG_M3_GPART_RULES_BIU;
DROP TRIGGER TRG_M4_CORDER_RULES_BIU;
DROP TRIGGER TRG_M4_ORDER_ITEM_RULES_BIU;
DROP TRIGGER TRG_M5_DELIVERY_RULES_BIU;
DROP TRIGGER TRG_M5_PAYMENT_RULES_BIU;

PROMPT Dropping indexes...
DROP INDEX M1_IDX_MEMBER_TYPE_STATUS;
DROP INDEX M1_IDX_ADDRESS_MEMBER_LABEL;
DROP INDEX M2_IDX_REST_CAT_STATUS;
DROP INDEX M2_IDX_MENU_CAT_AVAIL;
DROP INDEX M3_IDX_ORD_MEMBER_STAT_DT;
DROP INDEX M3_IDX_ORDER_ITEM_ITEM_QTY;
DROP INDEX M4_IDX_GRP_LEADER_STAT_DT;
DROP INDEX M4_IDX_GRP_PART_STAT;
DROP INDEX M5_IDX_PAY_ORD_STAT_DT;
DROP INDEX M5_IDX_VR_VOUCHER_MEMBER_DATE;

PROMPT Dropping sequences...
DROP SEQUENCE M1_MEMBER_ID_SEQ;
DROP SEQUENCE M1_MEMBER_TYPE_ID_SEQ;
DROP SEQUENCE M2_ADDRESS_ID_SEQ;
DROP SEQUENCE M2_VOUCHER_REDEMPTION_ID_SEQ;
DROP SEQUENCE M3_RESTAURANT_ID_SEQ;
DROP SEQUENCE M3_GROUP_ORDER_ID_SEQ;
DROP SEQUENCE M4_MENU_ITEM_ID_SEQ;
DROP SEQUENCE M4_ORDER_ITEM_ID_SEQ;
DROP SEQUENCE M5_ORDER_PAYMENT_ID_SEQ;
DROP SEQUENCE M5_PAYMENT_ID_SEQ;

