-- SHOPGRAB ASSIGNMENT DDL
-- STEP 0: DROP EXISTING TABLES (SAFE RE-RUN)

SET DEFINE OFF;

DROP TABLE VOUCHER_REDEMPTION CASCADE CONSTRAINTS PURGE;
DROP TABLE PAYMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DELIVERY CASCADE CONSTRAINTS PURGE;
DROP TABLE DELIVERY_COMPANY CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE GROUP_ORDER_PARTICIPANT CASCADE CONSTRAINTS PURGE;
DROP TABLE GROUP_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE VOUCHER CASCADE CONSTRAINTS PURGE;
DROP TABLE MENU_ITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE ITEM_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS PURGE;
DROP TABLE RESTAURANT_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE ADDRESS CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER_TYPE CASCADE CONSTRAINTS PURGE;

-- DROP SEQUENCES
DROP SEQUENCE M1_MEMBER_ID_SEQ;
DROP SEQUENCE M1_MEMBER_TYPE_ID_SEQ;
DROP SEQUENCE M2_ADDRESS_ID_SEQ;
DROP SEQUENCE M2_VOUCHER_REDEMPTION_ID_SEQ;
DROP SEQUENCE M3_RESTAURANT_ID_SEQ;
DROP SEQUENCE M3_GROUP_ORDER_ID_SEQ;
DROP SEQUENCE M4_MENU_ITEM_ID_SEQ;
DROP SEQUENCE M4_ORDER_ITEM_ID_SEQ;
DROP SEQUENCE M5_ORDER_PAYMENT_ID_SEQ;
DROP SEQUENCE M5_PAYMENT_ID_SEQ;

cl scr
PROMPT Tables dropped successfully

